update: insecure

schedule: "every week on sunday"

search: False

requirements:
  - requirements-dev.txt:
      update: insecure
      pin: False
  - requirements.txt:
      update: True
      pin: True
 
label_prs: 
  - automerge
  - dependencies
bug: 
